### ISSUE TITLE
can not even install

### ISSUE THREAD

**Issue by okyeahsoumm** [jrbudda/Vivecraft_113#24]
When I open the installer it opens a winrar file and not the installer is this normal

**Comment by Techjar** [comment]
You need to install Java. The Java included with Minecraft is not installed to the system.

**Comment by okyeahsoumm** [comment]
what

**Comment by okyeahsoumm** [comment]
it is an exe oh well

**Comment by Techjar** [comment]
You mean the exe opens in WinRAR? What files do you see?

**Comment by okyeahsoumm** [comment]
nvm it is confusing now

**Comment by okyeahsoumm** [comment]
its fixed yet not

**Comment by okyeahsoumm** [comment]
and now oculus wont open well great

**Comment by Techjar** [comment]
Sounds like you somehow managed to associate exe files with WinRAR, which is very bad and difficult problem to solve.

**Comment by okyeahsoumm** [comment]
how do i closed this the jar did not open and instead opened on win rar and also i think i fixed it now

**Comment by okyeahsoumm** [comment]
so i think i am done here thanks

**Comment by fionafibration** [comment]
These resources may be helpful if additional file association issues persist.

https://www.thewindowsclub.com/fix-unable-to-open-exe-lnk-files-windows-7

https://www.thewindowsclub.com/rebuild-corrupt-icon-cache-with-icon-cache-rebuilder

http://forum.thewindowsclub.com/windows-tips-tutorials-articles/33985-fix-exe-files-won-t-open-windows-7-a.html
